### PR TITLE
rewrite import paths to use new org's code

### PR DESCRIPTION
**Pull request by keks**

### CODE REVIEW

**Comment by Kubuxu** [comment]
The gx dependency needs an update too, to a version that contains correct dsvc-import path. You can try if the gx dependency is correct by doing `gx-go rewrite` and all dependencies should be changed into `gx/ipfs/Qm...`.

`gx-rewrite --undo` to revert back.

**Comment by Kubuxu** [comment]
Are you  still interested in working on it?
I can take it over.

**Comment by keks** [comment]
It seems this has been done elsewhere already. Close this if you agree

**Comment by Kubuxu** [comment]
Ok, thanks either way.

**Pull request closed without merging**
